name: macOS App – Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build and test
        run: |
          xcodebuild test \
            -project "Transcribe Audio.xcodeproj" \
            -scheme "Transcribe Audio" \
            -destination "platform=macOS" \
            -enableCodeCoverage YES \
            | xcpretty && exit ${PIPESTATUS[0]}
